# Generated by Django 5.0.7 on 2024-07-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0002_alter_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
