# Generated by Django 5.0.7 on 2024-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts'),
        ),
    ]
