# Generated by Django 5.0.7 on 2024-07-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0007_alter_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpost.post'),
        ),
    ]
